### ISSUE TITLE
Generating IAV token generates odd number of arguments error

### ISSUE THREAD

**Issue by Siraris** [Dwolla/dwolla-v2-ruby#44]
I was sent over here by my developer relations contact.  I am having a weird issue that I'm struggling to diagnose.  I thought it might be something related to our codebase, but a couple things is making me think it's related to this library:

1.  This flow has worked for months now, and the code has not changed.  All of a sudden, it doesn't work, but did work as of 10/18/18 (nothing has changed between then and now).
2.  There's nothing on our end that's inbetween the call being made, and the actual error being produced.

We're trying to generate an IAV token to pass to the dwolla.js widget to initialize bank authorization.  The entirety of our code is as follows:

`response = Client.post("customers/#{customer_id}/iav-token")
        response.token`

Where Client.post calls

`$dwolla.auths.client.post endpoint, params`

Where endpoint is what's being passed in in that string.  I've verified that the correct customer_id is being passed, and correlates with a valid account.  I asked our contact if the account not having certified beneficial ownership yet might be causing an issue, and he said no.

Any help would be appreciate on this as it's interfering with our customers experience.  I'll also post the stack trace below:

By the way, the error is coming directly from the Client.post call.

`[127.0.0.1] [ip-172-28-234-124.ec2.internal] odd number of arguments for Hash excluded from capture: No project_id specified
[127.0.0.1] [ip-172-28-234-124.ec2.internal]
[127.0.0.1] [ip-172-28-234-124.ec2.internal] ArgumentError (odd number of arguments for Hash):
[127.0.0.1] [ip-172-28-234-124.ec2.internal]
[127.0.0.1] [ip-172-28-234-124.ec2.internal] hashie (3.5.7) lib/hashie/extensions/indifferent_access.rb:46:in `[]'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] hashie (3.5.7) lib/hashie/extensions/indifferent_access.rb:46:in `[]'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] dwolla_v2 (1.2.2) lib/dwolla_v2/super_hash.rb:9:in `=='
[127.0.0.1] [ip-172-28-234-124.ec2.internal] dwolla_v2 (1.2.2) lib/dwolla_v2/error.rb:44:in `=='
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/rescuable.rb:94:in `include?'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/rescuable.rb:94:in `rescue_with_handler'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/rescuable.rb:97:in `rescue_with_handler'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/rescuable.rb:164:in `rescue_with_handler'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_controller/metal/rescue.rb:23:in `rescue in process_action'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_controller/metal/rescue.rb:20:in `process_action'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/notifications.rb:166:in `block in instrument'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/notifications.rb:166:in `instrument'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] searchkick (3.0.0) lib/searchkick/logging.rb:209:in `process_action'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activerecord (5.1.6) lib/active_record/railties/controller_runtime.rb:22:in `process_action'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/abstract_controller/base.rb:124:in `process'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionview (5.1.6) lib/action_view/rendering.rb:30:in `process'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_controller/metal.rb:189:in `dispatch'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_controller/metal.rb:253:in `dispatch'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:31:in `serve'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `each'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/journey/router.rb:33:in `serve'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/routing/route_set.rb:844:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack (2.0.6) lib/rack/etag.rb:25:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack (2.0.6) lib/rack/conditional_get.rb:25:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack (2.0.6) lib/rack/head.rb:12:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/cookies.rb:613:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activerecord (5.1.6) lib/active_record/migration.rb:556:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/callbacks.rb:97:in `run_callbacks'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] railties (5.1.6) lib/rails/rack/logger.rb:36:in `call_app'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] railties (5.1.6) lib/rails/rack/logger.rb:24:in `block in call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `block in tagged'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/tagged_logging.rb:69:in `tagged'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] railties (5.1.6) lib/rails/rack/logger.rb:24:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/request_id.rb:25:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack (2.0.6) lib/rack/method_override.rb:22:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack (2.0.6) lib/rack/runtime.rb:22:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] activesupport (5.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] actionpack (5.1.6) lib/action_dispatch/middleware/static.rb:125:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] sentry-raven (2.7.4) lib/raven/integrations/rack.rb:51:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] railties (5.1.6) lib/rails/engine.rb:522:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] puma (3.10.0) lib/puma/configuration.rb:225:in `call'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] puma (3.10.0) lib/puma/server.rb:437:in `process_client'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] puma (3.10.0) lib/puma/server.rb:301:in `block in run'
[127.0.0.1] [ip-172-28-234-124.ec2.internal] puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'`

**Comment by sausman** [comment]
Hey @Siraris,

I'm not entirely sure what's going on here, but I wonder if it's related to the issue here https://stackoverflow.com/questions/48024581/ruby-odd-number-of-arguments-for-hash-error ?

That issue seems to be caused by too many `Hash` initializations, so I wonder if there's a way to either raise the limit using some sort of Ruby VM environment variable or reduce the number of initializations here: https://github.com/Dwolla/dwolla-v2-ruby/blob/master/lib/dwolla_v2/super_hash.rb#L9 (if that's even the problem).

Another thing worth trying would be upgrading to the latest `dwolla-v2` just to see if that does anything.

**Comment by Siraris** [comment]
@sausman I installed 2.2.1 today and that didn't fix anything :\ we were on 1.2.7 before! 

I'm not sure if that SO is applicable, but you would obviously know better than I.  Like I mentioned, it's odd that this would have worked fine a few weeks ago, and now all of a sudden explode, no?

**Comment by Siraris** [comment]
@sausman Do you need something from me on this?  This is impacting our clients so if you can keep me in the loop I'd appreciate it.  Just seems odd that we're the only person reporting this.

**Comment by sausman** [comment]
Hey @Siraris,

It does seem odd and it's a hard problem to reproduce, which leads me to believe it has something to do with your environment's Ruby VM being overloaded in some way? A few ideas:

- Look into Ruby VM tuning. I'm wondering if the environment your application is running in is causing the Ruby VM to run with constrained resources by default? I'm not too knowledgeable on this, but it could explain why we haven't seen it pop up elsewhere. I think it's just a matter of tweaking some environment variables.
- I noticed your `Client.post` method calls `$dwolla.auths.client` to create a new token each time a request is made. You could reduce the number of calls by reusing the token for subsequent requests to reduce the amount of work your app is doing.
- We could try tweaking some code in this library, but I'm not sure what the fix would be. If you're able to provide a failing test or an example file that reproduces the error we could try our hand at getting the error to go away. https://bundler.io/v1.12/git.html has some info on how to have your app use either a local git repo containing the `dwolla_v2` gem or a forked repository on GitHub if you want to play around with it.

I'm sorry to hear it's impacting your clients :(. I wish I could be of more help, but that's all I can think of at the moment. I'll continue to give it some thought and will let you know if anything else comes to mind.

**Comment by Siraris** [comment]
@sausman I'm a little confused about your response.  This is happening on both our EC2 production machine, and also on my local development server.  I can't imagine we're resource constrained on our EC2 server - we're running an M5 xlarge - and if one simple request to the Dwolla API using your library is overloading our VM, I feel like there's larger issues going on here.

Odd number of arguments for a hash simply means that there are an odd number of key value pairs (too many keys, not enough pairs).  So something we're doing is generating this, and causing the library to fail.  Coincidentally I opened an issue months ago about this, but it was something we were doing in building out the error message we were receiving back from the library, and was totally on us.  But from what I can tell, this is coming from within your gem.  I've checked what we're passing into the dwolla.auths.client call and it's simply a string, that's it.  So my assumption is a malformed hash is being generated by your library.  

Does this make sense?

**Comment by sausman** [comment]
@Siraris Ah ok. I was actually referring to the Ruby VM (e.g. https://medium.com/@zanker/the-ruby-vm-and-how-apps-break-part-2-e8b4620ad50d). It sounds like you have some pretty beefy EC2 instances, so hopefully it's solvable by throwing some more resources at the Ruby VM. Not sure if that's the problem tho.

If you run the following example do you get the same error you're seeing in your application?

```bash
$ git clone git@github.com:Dwolla/dwolla-v2-ruby.git
$ cd dwolla-v2-ruby
$ git checkout examples
$ bundle install
$ export \
    DWOLLA_ID="..." \
    DWOLLA_SECRET="..." \
    DWOLLA_ENV="..." \
    DWOLLA_CUSTOMER_ID="..."
$ bundle exec ruby examples/iav_token.rb
```

When I run that I'm getting:

```
#<DwollaV2::Response response_status=200 response_headers={"date"=>"Tue, 18 Dec 2018 20:49:43 GMT", "content-type"=>"application/vnd.dwolla.v1.hal+json", "content-length"=>"251", "connection"=>"close", "set-cookie"=>"__cfduid=d9bbb066833e2537fb39442a9a9d6aa141545166183; expires=Wed, 18-Dec-19 20:49:43 GMT; path=/; domain=.dwolla.com; HttpOnly", "x-request-id"=>"2238071b-332c-426b-b9a4-5b5bf2fd7f69", "expect-ct"=>"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", "server"=>"cloudflare", "cf-ray"=>"48b47f672e8ac641-MSP"} {"_links"=>{"self"=>{"href"=>"https://api-sandbox.dwolla.com/customers/bcd4155e-33a9-47b5-9b2e-c969ef4f2534/iav-token", "type"=>"application/vnd.dwolla.v1.hal+json", "resource-type"=>"iav-token"}}, "token"=>"0cayQc9vXSiKmKrMuwsE9rZ64dVA4q9YRR7KtQBvq2zgAAYTaw"}>
```

If that example gives the same error you are getting in your app, I would guess the client library is getting back an unexpected response that it needs to handle more gracefully and we can look into why the server is returning a malformed response.

If the example does work, I'm not sure how much assistance we'll be able to provide without profiling your application using something like https://github.com/ruby-prof/ruby-prof. My second suggestion in my earlier comment (reusing tokens across multiple requests) could be an easy way to reduce the amount of work your app has to do.

If this gem is contributing to performance issues, we will see what we can do to improve it (we're open to suggestions/PRs!), but it relies on some external gems like Hashie where a lot of the "magic" happens and I think some of the design decisions will limit our ability to make any drastic performance gains in the near term.

**Comment by Siraris** [comment]
@sausman just wanted to give you an update.  For whatever reason, the odd number of arguments error has vanished from my local machine.  I'm befuddled as to whats' going on, or what caused it in the first place, but it's not there anymore.  Due to a series of unfortunate events, I think this was actually not the problem with production, and it was another thing entirely.  So sorry to waste your time on this!  I'll close.
